---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS CloudFormation MDLC Sample Template.
Parameters:
  Stage: {Type: String, Default: 'test'}
  Region: {Type: String, Default: 'USAmazon'}  
  MDLCWorkshopPublicArtifactBucket:
    Type: String
    Default: "kk-public-ws-bucket"
  InputDataKey:
    Type: String
    Default: "input-data"
  LambdaLayerArtifactKey:
    Type: String
    Default: "python-libs"
  PandasLambdaLayerArtifactKey:
    Type: String
    Default: "python-libs/python36-pandas24.zip"
  SklearnLambdaLayerArtifactKey:
    Type: String
    Default: "python-libs/python36-sklearn203.zip"
Resources:
  MDLCS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
  InputDataObject:
    Type: Custom::S3Object
    Properties:
      ServiceToken: !GetAtt CopyS3ResourceFunction.Arn
      Source:
        Bucket: !Ref MDLCWorkshopPublicArtifactBucket
        Key: !Ref InputDataKey
      Target:
        Bucket: !Ref MDLCS3Bucket
        Key: !Ref InputDataKey
  LayerArtifactObject:
    Type: Custom::S3Object
    Properties:
      ServiceToken: !GetAtt CopyS3ResourceFunction.Arn
      Source:
        Bucket: !Ref MDLCWorkshopPublicArtifactBucket
        Key: !Ref LambdaLayerArtifactKey
      Target:
        Bucket: !Ref MDLCS3Bucket
        Key: !Ref LambdaLayerArtifactKey

Outputs:
  StackArn:
    Description: Don't remove this output! 
    Value: {Ref: 'AWS::StackId'}
